### ISSUE TITLE
Help with getting dashboard and slack examples running.

### ISSUE THREAD

**Issue by Analect** [ibm-et/defrag2015#1]
@parente 
There are some fantastic ideas in your usage of notebooks here, especially the more advanced spark and slack-related ones.  I found the accompanying blog-post here: 
http://www.spark.tc/developing-data-products-with-jupyter-notebooks-and-spark/

I was wondering if you might be able to point me in the right direction to fill in the gaps in terms of getting these more advanced examples up and running. 

I can see that dashboard.ipynb is leveraging a number of the jupyter-incubator projects ... 'dashboards', 'declarativewidgets' and maybe even 'sparkmagic'. I don't think any of these have been folded into Jupyter core, as yet ... in which case, in order to prime a Jupyter set-up for dashboard.ipynb, is it enough to follow the 'Develop' steps in the likes of the jupyter-incubator/dashboards readme ... or is it a bit more involved to get things up and running?

On the slack example (discussion.ipynb), would it be possible to add to this repo the python script you use to interface back into slack in order for the jupyter-bot to work.  Is it leveraging something like: https://github.com/slackhq/python-rtmbot
Some of the steps involved would be very valuable.

Thanks.
Colum

**Comment by parente** [comment]
Thanks for the interest and request. 

> I was wondering if you might be able to point me in the right direction to fill in the gaps in terms of getting these more advanced examples up and running.

I think the quick answer to your problems is for me to turn this repo into a binder (https://mybinder.org) so that you can click to use all of the notebooks in a temporary Jupyter server with all the pre-reqs installed. It won't get you running locally (for that, there are things like jupyter/docker-stacks), but it will let you try everything with near zero hassle.

> I don't think any of these have been folded into Jupyter core, as yet ... in which case, in order to prime a Jupyter set-up for dashboard.ipynb, is it enough to follow the 'Develop' steps in the likes of the jupyter-incubator/dashboards readme ... or is it a bit more involved to get things up and running?

We just released a pip installable package for dashboards, declarative widgets, etc. If you really want to get everything locally, you need to follow the jupyter setup instructions first (3.2.x only as of right now), then pip install all the incubator extension atop that. We are building a docker image (https://hub.docker.com/r/jupyterincubator/dashboards-widgets-cm-notebook/) for our custom tmpnb site, https://jupyter.cloudet.xyz (which btw has other examples of dashboards, widgets, etc.) so you could also pull that. But it's not versioned well, and is updated quasi-regularly.

> On the slack example (discussion.ipynb), would it be possible to add to this repo the python script you use to interface back into slack in order for the jupyter-bot to work.

Actually, the entire bot is done in a notebook too. See the slack_bot.ipynb in the notebooks dir. It probably needs a bit of doc, but the flow is:
1. Setup slack integrations. (Yes. I need to doc this.)
2. Open the discussion.ipynb notebook. Fill in whatever keys you want (if you want) and run it top to bottom.
3. Open the slack_bot.ipynb notebook. Fill in the Slack keys / URLs for your account. Run it top to bottom.
4. Modify / run cells in discussion.ipynb to expose them via the Slack channel.

**Comment by parente** [comment]
TODOs
- [x] binder config
- [ ] ~~index.ipynb as place to doc how to use all the demos when opened in binder~~
- [x] better doc in the slack notebooks
- [x] more URLS to where you get all the goods beyond the demos

**Comment by Analect** [comment]
@parente 
Appreciate your detailed response. I'll run through some of your suggestions.  Just so I understand, for this to work on binder, is it sufficient to add a requirements file for the required python packages ... or do you need to specify a dockerfile of some sort?

**Comment by parente** [comment]
Either / or. For these examples specifically, a requirements.txt will suffice since they're all python.

And btw, no reason for you to have to do this on Binder yourself. I'll add a Binder badge to the README where a passer-by can just click and get a running notebook with the samples.

**Comment by parente** [comment]
Haven't forgotten about this. Should have time to work on it this week.

**Comment by parente** [comment]
Added a Dockerfile and requirements.txt to get Binder to work. The README now has a Launch Binder button. Also added a link to the jupyter-incubator/showcase repo for more examples.

**Comment by parente** [comment]
More doc in the slack notebooks. Fixed a missing dep for slack_bot.ipynb. Unfortunately, the slack bot cannot be used from Binder: it requires an additional HTTP port open for the slack_bot kernel to receive webhook messages from Slack, and Binder has no special provision for such a thing. Still, the Dockerfile, requirements.txt, and text in the notebooks themselves should provide a basic set of steps for running the slack examples on your own.

**Comment by Analect** [comment]
@parente 
Thank you. I'll give this a try. I'll close this for now.
